[package]
name = "test-spider-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = { version = "2.27.31", features = ["cache", "sitemap", "chrome", "smart", "chrome_stealth", "chrome_intercept"] }
spider_transformations = "2.27.31"
tokio = { version = "1.43.0", features = ["full"] }
